import fs from 'node:fs'
import path from 'node:path'
import type { Connect } from 'vite'
import { defineConfig, loadEnv } from 'vite'

const DCJ_CONFIG_PATH = 'public/victims/dcj-config.js'
const CALLBACK_HTML = 'public/callback/index.html'

/** Serve /callback and /callback/ as static HTML — Slidev SPA fallback would otherwise win. */
function callbackPagePlugin() {
  const serveCallback: Connect.NextHandleFunction = (req, res, next) => {
    const pathname = req.url?.split('?')[0] ?? ''
    if (pathname !== '/callback' && pathname !== '/callback/') {
      next()
      return
    }
    const file = path.resolve(CALLBACK_HTML)
    fs.readFile(file, (err, data) => {
      if (err) {
        next(err)
        return
      }
      res.setHeader('Content-Type', 'text/html; charset=utf-8')
      res.end(data)
    })
  }

  return {
    name: 'callback-page',
    configureServer(server: { middlewares: Connect.Server }) {
      server.middlewares.use(serveCallback)
    },
    configurePreviewServer(server: { middlewares: Connect.Server }) {
      server.middlewares.use(serveCallback)
    },
  }
}

/** Inject GitHub OAuth settings into static DCJ victim pages (public/ is not processed by Vite). */
function dcjConfigPlugin(mode: string) {
  return {
    name: 'dcj-config',
    configResolved(config: { root: string }) {
      const env = loadEnv(mode, config.root, '')
      const clientId = env.VITE_GITHUB_OAUTH_CLIENT_ID || '178c6fc778ccc68e1d6a'
      const scope = env.VITE_GITHUB_OAUTH_SCOPE || 'read:user'
      const out = path.join(config.root, DCJ_CONFIG_PATH)
      fs.mkdirSync(path.dirname(out), { recursive: true })
      fs.writeFileSync(
        out,
        `// Generated by vite.config.ts — do not edit; set VITE_GITHUB_OAUTH_CLIENT_ID in .env\n` +
          `window.__DCJ_GITHUB_CLIENT_ID__=${JSON.stringify(clientId)};\n` +
          `window.__DCJ_GITHUB_OAUTH_SCOPE__=${JSON.stringify(scope)};\n`,
      )
    },
  }
}

export default defineConfig(({ mode }) => ({
  plugins: [dcjConfigPlugin(mode), callbackPagePlugin()],
}))
